### ISSUE TITLE
general questions, totally new to typescript and trying to get this to run

### ISSUE THREAD

**Issue by q2000foo** [RienNeVaPlus/wikifolio#1]
Hello there,

thank you very much for sharing your code! I gave it a try but couldn't get it to run thus far
--- which certainly is because of my complete lack of experience with javascript/typescript.

Would it be possible to provide a little shell script (or example typescript files) for starting from scratch
(I'm on Ubuntu 18 LTS), and helping complete novices like me to get typescript, and consequently this repo, to run?
This repo has some pretty code snippets in the readme already, but I seem to fail putting the puzzle pieces together.

Alternatively, I would very much appreciate some help on what I tried so far:

1. installing typescript and wikifolio globally

```
sudo npm install -g typescript
sudo npm install -g wikifolio
```

2. creating a toy script wikifolio.ts, containing the lines:

```
import {Wikifolio} from "/usr/local/lib/node_modules/wikifolio";

var email = "thisIsMy@emailAddress.de";
var password = "verySecretPassword";
const wiki = new Wikifolio({email, password});

const wikifolio = wiki.wikifolio('wfobserver');
console.log(await wikifolio.trades({pageSize: 100, page: 1}));
```

Note that I changed the line 

`import {Wikifolio} from "wikifolio";`

because this was throwing an error

> wikifolio.ts:1:25 - error TS2307: Cannot find module 'wikifolio' or its corresponding type declarations.

that is now apparently resolved by using the absolute path to the module.

3. then tried to compile the file via

`tsc wikifolio.ts`

.. but this throws a compile-time error

> wikifolio.ts:8:13 - error TS1378: Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher.
8 console.log(await wikifolio.trades({pageSize: 100, page: 1}));

This is essentially where I got entirely lost, been trying to go for 

'tsc wikifolio.ts --module esnext --target es2017'

.. but then it's back at not finding the module anymore:

> wikifolio.ts:1:25 - error TS2307: Cannot find module '/usr/local/lib/node_modules/wikifolio' or its corresponding type declarations.
> 1 import {Wikifolio} from "/usr/local/lib/node_modules/wikifolio";

4. This is seemingly just the compiling. Is it possible to run the compiled script as a process in the terminal?

These lines likely give you an idea of my complete lack of knowledge of typescript. Any help would be much appreciated. Cheers!

**Comment by RienNeVaPlus** [comment]
Hi,

thanks for reaching out. The project is very early alpha right now, please keep that in mind.
However, I've fixed a few problems and created an [example](https://github.com/RienNeVaPlus/wikifolio-example) for you.
Please use the new `v0.1.3` release and let's me know if you manage to run it.

**Comment by q2000foo** [comment]
Hi,

thanks a lot for the quick help, your  example scripts worked like a charm! It would surely have required me a longer time to figure out on my own how to set everything up, so this was very instructive. There may be some more of those basic questions at later point, but for now this allows me toying around a bit already ; ) So once more, thank you!

Cheers
