### ISSUE TITLE
Buy with orderType Quote causes Missing UnderlyingQuote Error

### ISSUE THREAD

**Issue by danielrsantana** [RienNeVaPlus/wikifolio#10]
I'm using this solution to develop a nodeJS terminal app to simulate stock operations. 

Everything all right when buying with `limit` as orderType but something goes wrong when using `quote` instead. Am I missing some parameter?

## Expected Behavior
When calling the buy method with `quote` as typeOrder the operation should work just like 'limit' orders.

## Current Behavior
The following error appears:

```bash
# Unknown Error: Unable to submit order (Bei Requoteorders muss das UnderlyingQuote angegeben werden.)
```

## Steps to Reproduce

1) NodeJS, Yarn and Typescript

2) Code to buy stocks (simplified to make it easier to find the possible cause)

**wikifolio.services.ts**
```js
import Api, { OrderParam } from 'wikifolio';

const API_KEY = 'HIDDEN DUE SECURITY REASONS';
const SAMPLE_ISIN = 'DE000LS9NMQ9';

const getExpirationDate = (): Date => {
  const now = new Date();
  now.setMinutes(now.getMinutes() + 30);
  return new Date(now);
};

export const buyWikifolio = async (
  email: string,
  password: string,
  order: Partial<OrderParam>
) => {
  const api = new Api({ email, password });
  const wikifolio = api.wikifolio(API_KEY);

  // with **_quote_** the error (Bei Requoteorders muss das UnderlyingQuote angegeben werden) occurs
  const orderType:any = 'limit';
  
  order = {
    ...order,
    orderType,
    expiresAt: getExpirationDate()
  };

  console.log('this is my order', order);

  return await wikifolio.buy(order);
};
```

**index.ts**
```js
import { buyWikifolio } from './services/wikifolio.services';
import { Order, OrderParam } from 'wikifolio';

const order: Partial<OrderParam> = {
  amount: 2,
  limitPrice: 100,
  underlyingIsin: 'DE000LS9NMQ9',
};

buyWikifolio(email, password, order)
  .then((result: Order) => {
    console.log(result);
  })
  .catch((error) => console.log(error))
  .finally(() => process.exit());
```

**package.json**
```json
  "dependencies": {
    "request": "^2.88.2",
    "wikifolio": "^0.3.3"
  },
  "devDependencies": {
    "typescript": "^4.4.3"
  }
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "module": "CommonJS",
    "noImplicitAny": true,
    "outDir": "build",
    "preserveConstEnums": true,
    "removeComments": true,
    "sourceMap": false
  },
  "include": ["src/**/*", "services", "index.ts"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```

## Context (Environment)
Trying to execute a quote operation. In the following screenshot I have two examples of the response the API call is giving me. 

In the first attempt I tried to send all the possible values and in the second one only the limitPrice, amount, underlyingIsin, orderType and expiresAt.

![image](https://user-images.githubusercontent.com/11296189/133440673-6654b4a2-e59d-4667-99aa-4c19fda73715.png)

Thanks in advance

**Comment by RienNeVaPlus** [comment]
Implemented by jekru in v0.3.4
